### ISSUE TITLE
Epic: general reactions with stochastic simulations

### ISSUE THREAD

**Issue by jcschaff** [virtualcell/vcell#1035]
### Motivation
currently only mass action like reactions are compatible for stochastic simulations in vcell.  While this is ideal and provides the best statistics, users have requested to allow stochastic simulations of non-mass action kinetics as well - possibly with a model warning which can be ignored.

### Tasks
- [ ] general reactions in math models for Gibson solver
- [ ] general reactions in math models for NFSim solver
- [ ] general reactions in math models for Smoldyn solver
- [ ] #166
