### ISSUE TITLE
Epic: modern auth with Keycloak OIDC

### ISSUE THREAD

**Issue by jcschaff** [virtualcell/vcell#1037]
### Motivation
- choose a third party solution for authentication and some authorization which provides support for OpenID Connect (OIDC).  Moving over to such a OIDC provider gives us an opportunity to 
   - externalize and modernize user account management (e.g. passwordless access, 2FA, change passwords, verify passwords).
   - decouple vcell user credentials from vcell application and vcell database.

- solutions
   - Keycloak is an open source solution which can be self-hosted.  This is the obvious first choice during development but will have some security burden if made to be the permanent production solution.
   - Auth0.com is a commercial offering with several plans, but upcharges for multiple social media logins.

### Completion Criteria
- all VCell services and APIs use single Keycloak instance for Authentication and encode some basic Role Based Access Control (e.g. admin, power user).

### Tasks
- [ ] #155 
- [ ] integrate Auth flows using Keycloak for API and web apps.
- [ ] integrate Auth flow using Keycloak for Java client and admin CLI.
- [ ] install secure production Keycloak instance.
- [ ] load VCell user credentials into Keycloak and test on Alpha site.
- [ ] deploy Keycloak to production and remove hashed passwords from database.

**Comment by jcschaff** [comment]
done with Phase I - production VCell uses development Auth0 tenant for authentication.

Phase II (moving to a production Auth0.com tenant) is needed soon @AvocadoMoon @moraru
