### ISSUE TITLE
Story: VCell Server Serve N5 Data

### ISSUE THREAD

**Issue by AvocadoMoon** [virtualcell/vcell#1071]
Being able to take simulation data, convert it to N5 data format, and serve it to clients remotely.

### Requirements

- Take simulation data stored in VCell's servers and convert to N5 data on a users request
- Have that data hosted at an endpoint which uses an API that is widely adopted

### Tasks

- [x] #980 
- [x] #1000 
- [x] #949 
- [x] #990 
- [x] #983 
- [x] Make folders for each user at the S3 endpoint storage, and then put the resulting simulation storage in there.
- [x] https://github.com/virtualcell/vcell/pull/1081
- [x] Better naming scheme for exported N5 files that include human readable metadata

### Production Tasks
- [x] #1116 

### Future

- #984

**Comment by AvocadoMoon** [comment]
Change interface to variable in docker-compose-small.
