### ISSUE TITLE
VCell Export Table GUI and N5 Export GUI Ezequiels Revisement

### ISSUE THREAD

**Issue by AvocadoMoon** [virtualcell/vcell#1181]
### Problem
The GUI used for exporting to N5 utilizes terminology such as dataset which can be confusing for them. In addition the exported data table GUI can be improved to have it more readable. 

### Tasks
- [x] Label "Export Details" instead of in the text box, and label around table
- [x] Colorize key words, these keywords signify different entries within the text box
- [x] Add icons in table (can be determined from application type, icons stored in resources) 
   - [x] Stochastic vs. Deterministic
   - [x] NFSIM vs. Spring Salad
   - [x] Spatial vs. Non-Spatial
- [x] Resize bottom table
- [x] Implement similar filters in job simulations table 
     - [x] Export Format
     - [x] Time span
     - [x] Changed Parameter/all
- [x] 10 lines of table (subjective, to large right now)
- [x] Add some border to the table and text area
- [x] Parameter values in separate table
- [x] Export dialog should throw error if someone attempts to name file something they shouldn't

**Comment by AvocadoMoon** [comment]
Dan's Suggestions:

- Label "Export Details" instead of in the text box
- Colorize key words, these keywords signify different entries within the text box
- Add icons in table (can be determined from application type, icons stored in resources) 
   - Stochastic vs. Deterministic
   - NFSIM vs. Spring Salad
   - Spatial vs. Non-Spatial
- Resize bottom table
- Implement similar filters in job simulations table

**Comment by danv61** [comment]
Other ideas in no particular order:
Use Windows version for screenshots, looks much better than on linux
Check Account / View Simulation Jobs dialog box, it's very much alike your table
For some users the number of entries may become large, I suggest a time interval selector like in simulation job status (past 24 hours, past week, past month, all).
Indication if the original data used still exists (using sim id, job, task, job submission date)
Sorting by some columns: date of export(default), model name, application name, sim name...

**Comment by danv61** [comment]
Example of formatting a larger text based on named subparagraphs
![formatting](https://github.com/virtualcell/vcell/assets/29076329/185a5656-0fda-4c8c-a2ab-1e5bee24e506)

**Comment by danv61** [comment]
Check Account / View Simulation Jobs dialog box, it's very much alike your table (many columns are the same)

![image](https://github.com/virtualcell/vcell/assets/29076329/0d4ef5e2-ad6f-470b-8296-963203316562)

You don't necessarily need one column for each entry, you can concatenate for example the model and application names

**Comment by danv61** [comment]
For some users the number of entries may become large, I suggest a time interval selector like in simulation job status.

![image](https://github.com/virtualcell/vcell/assets/29076329/37fb1a80-f9ec-4454-8cce-8a688906c633)

**Comment by danv61** [comment]
You could provide a wealth of extra information to help the user remember what the biomodel is all about, the information is already loaded somewhere in the vcell client, you only need to get to it and use the existing visualization code to display it in some panel:

![image](https://github.com/virtualcell/vcell/assets/29076329/4476977a-ac4b-47ae-9b53-c0b9a869c8e8)
