### ISSUE TITLE
Story: Transition Field Data RPC To a RESTful Endpoint and Fix Bugs

### ISSUE THREAD

**Issue by AvocadoMoon** [virtualcell/vcell#1389]
### Problem
There are plenty of bugs regarding the field data feature within VCell
- Memory overflow
- HTTP packet size to large
- Miscommunication with the database
In addition the RPC communication method is convoluted, and requires time to understand.

### Solution
While trying to address these bugs, also transition the RPC endpoint into a restful endpoint

### Tasks

- [ ] Make the field data endpoint into one that is RESTful
- [x] Figure out file uploading for the field data endpoint
- [ ] Disable and remove the rpc methods that are present within the RPC service that are associated with field data
- [ ] Local runs using field data don't work because it's on server. Fix that so it retrieves that field data, then runs it locally on the VCell app
