### ISSUE TITLE
Expanding N5 Variable Support

### ISSUE THREAD

**Issue by AvocadoMoon** [virtualcell/vcell#983]
### Now
Currently the N5 export only supports volume variables due to there ease of data translation from the array of doubles that get returned from these variables to the N5 binary files that are chunked by time.

### Goal
Add more variables that can be exported, so that the user can have more options.

### Tasks To Achieve Goal

- [ ] Create a method for data conversion
    - [ ]  Figure out unit conversion for variables that have different units of measurement
    - [ ] For variables that aren't necessarily occupying a region in space (membranes cause infinite thin) make some method that blurs them into a region of space.

**Comment by AvocadoMoon** [comment]
Current rough draft.

`import math
import numpy as np

xshape = 4
yshape = 2
zshape = 4

xyz = np.zeros((xshape, yshape, zshape), int)

counter = 0
for xi in range(xshape):
    for yi in range(yshape):
        for zi in range(zshape):
            xyz[xi, yi, zi] = counter
            counter += 1

t = [xyz for i in range(6)]

print(xyz)

# Everyone of them only need to be held for the time interval that the chunk size is
# don't need to hold it for the whole for loop

# How do you write x,y,z and time in an array, lets assume its just a list with [x_i, y_i, z_i] is all thats needed for this example and its a append for each cord

x_chunk_num = math.ceil(xshape/2)
y_chunk_num = math.ceil(yshape/2)
z_chunk_num = math.ceil(zshape/2)
t_chunk_num = math.ceil(len(t)/2)

x_chunk_size = math.ceil(xshape / x_chunk_num)
y_chunk_size = math.ceil(yshape / y_chunk_num)
z_chunk_size = math.ceil(zshape / z_chunk_num)

volume = xshape * yshape * zshape
print(xyz.size)
chunkVolume = x_chunk_size * y_chunk_size * z_chunk_size
num_chunks = math.ceil(volume / chunkVolume)

current_chunks = [[] for j in range(num_chunks)]

time_chunks = 0



for time_slice in range(len(t)):
    counter = 0
    for xi in range(0, xshape,x_chunk_size):
        for yi in range(0, yshape, y_chunk_size):
            for zi in range(0, zshape, z_chunk_size):
                space_dict = {
                    "Chunk in Space": counter, 
                    "Time": time_slice,
                    "Chunk Data" : ""
                }
                space_dict.update({"Chunk Data": xyz[xi:x_chunk_size + xi, yi: yi+y_chunk_size, zi: zi+z_chunk_size]})
                current_chunks[counter].append(space_dict)
                counter += 1
    if((time_slice + 1) % t_chunk_num == 0):
        counter = 0
        print("======================================================")
        for k in range(len(current_chunks)):
            print(f"Blocks that would be written now: {current_chunks[k]} \n------------------------------")
        current_chunks = [[] for j in range(num_chunks)] # Erase the data written
    


for time_slice in range(len(t)):
    for spec_space_in_frame in range(num_chunks):
        space_dict = {
            "Chunk in Space": spec_space_in_frame, 
            "Time": time_slice,
            "Chunk Data" : ""
    }
        startIndex = lambda chunk, shape: (spec_space_in_frame * chunk) % shape
        endIndex = lambda chunk, shape: startIndex(chunk, shape) + chunk
        if((spec_space_in_frame + 1) == num_chunks):
            space_dict.update({"Chunk Data": xyz[startIndex(x_chunk_num, xshape):, startIndex(y_chunk_num, yshape):, startIndex(z_chunk_num, zshape):]})
            # space_dict.update({"x": xyz})
            # space_dict.update({"y": y[y_chunk * spec_space_in_frame:]})
            # space_dict.update({"z": z[z_chunk * spec_space_in_frame:]})
            current_chunks[spec_space_in_frame].append(space_dict)
            break

        # space_dict.update({"x": x[x_chunk * spec_space_in_frame: f(x_chunk)]})
        # space_dict.update({"y": y[y_chunk * spec_space_in_frame: f(y_chunk)]})
        # space_dict.update({"z": z[z_chunk * spec_space_in_frame: f(z_chunk)]})
        space_dict.update({"Chunk Data": xyz[startIndex(x_chunk_num, xshape): endIndex(x_chunk_num, xshape), startIndex(y_chunk_num, yshape): endIndex(y_chunk_num, yshape), startIndex(z_chunk_num, zshape):endIndex(z_chunk_num, zshape)]})
        current_chunks[spec_space_in_frame].append(space_dict)
    
    if((time_slice + 1) % t_chunk_num == 0):

        print("======================================================")
        for k in range(len(current_chunks)):
            print(f"Blocks that would be written now: {current_chunks[k]} \n------------------------------")
        current_chunks = [[] for j in range(num_chunks)] # Erase the data written
    




`

**Comment by AvocadoMoon** [comment]
Can potentially gain insight from other code blobs that are able to transfer membrane related data into other file formats.
